# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

jobs:
  tests:
    runs-on: ubuntu-latest
    name: UI Automation
    steps:
      - uses: actions/checkout@v2
      - name: Zalenium
        uses: ajinx/zalenium@1.1
      - name: Run test
        env:
          SELENIUM_HUB_HOST: 'localhost'
        run: mvn clean test